### ISSUE TITLE
Config Option: Bypass "Normal" mode 

### ISSUE THREAD

**Issue by fsargent** [rvaiya/warpd#85]
Hiya,
I've got a QMK keyboard with mouse keys enabled. I would prefer to use that setting for any local navigation but love the way that I can jump to a location using grid. I'd like a feature to make it so that while I can use grid, after picking its location it won't launch into "normal" mode.
Thanks!

**Comment by rvaiya** [comment]
You can already achieve this by hitting the exit key while in grid mode. Though I'm curious to know why you prefer controlling the mouse with your keyboard firmware. One of the goals of warpd is to obviate the need for such things. If normal mode isn't as usable as your keyboard firmware then I would consider it a bug.

**Comment by fsargent** [comment]
Normally I'd like to be able to use the grid to teleport, but I'd use the muscle memory I've already built using my customizations I've built into QMK for "normal" mouse movements. Warpd is great for big movements which take a long time when using keyboard based movements.

Mouse mode is only operational when holding down a key (my Nav layer, under my thumb) and so I know very clearly when I'm in mouse mode, and when I'm using a regular keyboard. Warpd feels unintuitive to me as it'll put me into normal mode where I have to use the escape key before I can type again. You already have a "one shot click" button which will escape normal mode once it's fired - this use case is very similar.

**Comment by rvaiya** [comment]
As mentioned, you can already achieve this by activating grid mode and using the exit key (e.g `A-M-g` ... `esc`), which will leave the pointer at the selected location. I'm not sure how what you are describing differs from this.

I would advise you to try hint mode in conjunction with the normal and oneshot keys, as it frees you from the burden of having to use additional chording after exiting grid mode.

The encouraged workflow is something like this:

-> Activate hint mode using `A-M-x`
-> Use `hjkl` to make adjustments (if any).
-> Press `n` to select the target and exit warpd.

**Comment by fsargent** [comment]
Ah, the request is to not have to hit escape. 

-> Activate hint mode using A-M-x
-> Use QMK to initiate any desired mouse clicks or refinements
-> Done, no escape key needed.

**Comment by rvaiya** [comment]
No worries. I still don't fully understand what you are proposing.

> -> Activate hint mode using A-M-x
> -> Use QMK to initiate any desired mouse clicks or refinements

This can be achieved by replacing `A-M-x` with `A-M-l` (oneshot hint mode). I'm not sure how you would expect a 'onehot grid mode' to work given that the user has to press some key to indicate that the selection is finished (in contrast to hint mode).

**Comment by rvaiya** [comment]
I'm closing this for now. I am not necessarily opposed to adding something like this if you can describe it in detail, so feel free to reopen the issue.

**Comment by fsargent** [comment]
Thanks - you're right, one shot hint mode does exactly what I want. Thanks!
